# https://taskfile.dev

version: '3'

vars:
  OUTPUT_NAME: Farental
  BASE_URL: https://api.farental.ch

tasks:
  release:
    cmds:
      - go build -o {{.OUTPUT_NAME}} -ldflags "-X 'farental/internal/config.BaseURL={{.BASE_URL}}'"